### ISSUE TITLE
fetch does not work

### ISSUE THREAD

**Issue by kevinoliveira** [matheussampaio/urionlinejudge-cli#17]
the command fetch does not even exist.
```
$ urionlinejudge fetch -n 1001
[*] Error:
[*] Command 'fetch' not found.
```
Is someone implementing it, or i can open a merge request?

**Comment by matheussampaio** [comment]
We do have a fetch command but it's not so useful yet. When I started this, I envisioned this function to fetch the description and examples of the question, and an option to fetch a random question (but one that I didn't submit before).

You're welcome to create a PR and start this.

I'll try to add tests and docker this week to make it easier to contribute. (:
