### ISSUE TITLE
Cpp is submitting as GoLang

### ISSUE THREAD

**Issue by kevinoliveira** [matheussampaio/urionlinejudge-cli#18]
```
$ urionlinejudge submit 1001.cpp
[*] Compilation error:
[*] 1001
```
I submitted a cpp code,but  the platform shows up a Go Lang submission![screenshot_2018-06-16_19-34-36](https://user-images.githubusercontent.com/14365975/41502945-b48bb972-719c-11e8-954d-8c8fa3055e0b.png)

on the code there are only support to few languages
https://github.com/matheussampaio/urionlinejudge-cli/blob/43ba53f855e16f820a31bcfaa7c49d17817f3ce8/src/cli.js#L9

https://github.com/matheussampaio/urionlinejudge-cli/blob/43ba53f855e16f820a31bcfaa7c49d17817f3ce8/src/uri/uri-online-judge.js#L43-L51

But Uri Online Judge allow more languages now
![screenshot_2018-06-16_19-38-04](https://user-images.githubusercontent.com/14365975/41502965-5c913728-719d-11e8-9d67-0b8d6093cddf.png)

How i can fix this? and how i can test the project?

**Comment by matheussampaio** [comment]
Thanks for creating the issue. It's been a while since I update this project. I'm afk right now, but I will check later today.

**Comment by matheussampaio** [comment]
Hey @kevinoliveira, I just refactored everything and published a new version. Can you install it and try again?

**Comment by kevinoliveira** [comment]
Still don't work, now the submission was done in python3:
`$ urionlinejudge submit 1001.cpp
`
![screenshot_2018-06-19_21-48-39](https://user-images.githubusercontent.com/14365975/41631402-c5d068b6-740a-11e8-9ce2-30f052430328.png)

and the puppeteer opens up the browser when the code was submitting, i also notice that the key pressing on login was very slow.

**Comment by kevinoliveira** [comment]
Everything works fine if i use, `$ urionlinejudge submit 1001.cpp --language c++`
Did you drop the auto language detection by the file extension?

**Comment by matheussampaio** [comment]
We never had a auto language detection (but it's a nice feature to have!) 😄 

Anyway, I released a new version removing the default language (used to be `python3`) and asking it when you call `urionlinejudge reset`.

**Comment by kevinoliveira** [comment]
Wonderful, i think the issue ends here.
